stages:
  - mirror

# Job pour synchroniser vers GitHub
mirror_to_github:
  stage: mirror
  image: bitnami/git:latest
#  only:
#    - main
  before_script:
    - git config --global user.email "ci@gitlab.com"
    - git config --global user.name "GitLab CI"
  script:
    - git remote add github https://CharlotteBertille4:GITHUB_TOKEN@github.com/CharlotteBertille4/les_premiers_site.git || true
    - git fetch --unshallow origin || true
    - git push github HEAD:refs/heads/main --force
  variables:
    GIT_STRATEGY: clone
    GIT_DEPTH: 0